language: python
sudo: false
python:
        - 2.7
        - 3.7
install:
        - pip install future
        - python install_deps.py
script:
        - python runtests.py
after_script:
        - rm -r .venv

